[package]
name = "xrpl-ledger-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
xrpl = "0.1.2"
serde_json = "1.0"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.20.1", features = ["native-tls"] }
futures-util = "0.3.31"